In [1]:
import numpy as np

In [5]:
#create simple array from the list 
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
#dinension of the array
print(arr.ndim)

2


In [8]:
#shape of the array 

print(arr.shape)

(2, 4)


In [9]:
#diamension of the array

print(type(arr))

<class 'numpy.ndarray'>


In [10]:
print(arr.data)

# Random Number Generatoer using numpy

In [11]:
from numpy import random
x= random.randint(100)
print(x)

40


In [12]:
#generate Random float

x=random.rand()
print(x)

0.590262881195591


In [15]:
from numpy import random 
x=random.randint(50)
print(x)

24


In [20]:
#generate value unser the range
from numpy import random 
x=random.rand(10)
print(x)

[0.23954923 0.82523837 0.54085846 0.57200373 0.58020703 0.16715895
 0.26187172 0.3181075  0.15720022 0.58655944]


In [21]:
from numpy import random 
x=random.rand()
print(x)


0.043430474006979636


In [22]:
#3. Generate Random array
 
from numpy import random

x= random.randint(100, size=(5))

print(x)
    

[68 82 40 67 46]


In [23]:
#3. Generate a 2-D array with 3 rows, each row containing 5 random integer
 
from numpy import random

x= random.randint(100, size=(3,5))

print(x)
    

[[33  2 40 99 10]
 [84 35 39 18 63]
 [55 44 79 10 42]]


# 2.4 Practical: creating Scalar in Numpy

In [25]:
#create simple array from the list 
arr = np.array([1,2,3,4,5,6,7,8])
arr


array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
np.amin(arr)

1

In [28]:
np.amax(arr)

8

In [30]:
np.mean(arr)

4.5

In [31]:
np.median(arr)

4.5

In [32]:
np.ptp(arr)

7

In [33]:
np.std(arr)

2.29128784747792

In [34]:
np.var(arr)

5.25

In [35]:
np.average(arr)

4.5

In [36]:
#create 1-D List

list1=[1,2,3]

In [37]:
#create 1-D  vertical List
list2=[[10],
      [20],
      [30]]

In [39]:
#create 1-D List

list1=[1,2,3]
#create 1-D  vertical List
list2=[[10],
      [20],
      [30]]

#create vector

vector1 =np.array(list1)
vector2= np.array(list2)

print("Horizontal Vector")
print(vector1)

print("Vertical Vector")
print(vector2)

Horizontal Vector
[1 2 3]
Vertical Vector
[[10]
 [20]
 [30]]


# 2.6 Practical Creating Matrix in Numpy

In [42]:
a=np.matrix('1 2; 3 4')
print("via stirng input :\n", a, "\n\n")

b=np.matrix([[5,6,7],[1,2,]])
print("via array -like input:\n",b)

via stirng input :
 [[1 2]
 [3 4]] 


via array -like input:
 [[list([5, 6, 7]) list([1, 2])]]


In [46]:
A = ([1,2,3],[4,5,6],[7,8,9])
np.transpose(A)



array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
import numpy as np
data = [23, 54, 66, 85, 92, 69, 54, 32, 96, 10, 98, 76, 90, 36, 65, 24, 98, 18, 20, 90]


Q1 = np.median(data[:10])
print(Q1, '\n')

Q3 = np.median(data[10:])
print(Q3, '\n')

IQR = Q3 - Q1
print(IQR)



60.0 

70.5 

10.5


# 2.10 PRATICAL: Array Broadingcasting in Numpy

In [12]:
a = np.array([1.0, 20., 3.0])
b = np.array([2.0, 2.0, 2.0])

a * b

array([ 2., 40.,  6.])

In [13]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a * b

array([2., 4., 6.])

# Calculate BMI of cricket players

In [7]:
#height of players
import numpy as np
hg_in = [61 ,66, 72, 69, 88, 98, 45, 66, 62, 77, 78]

#convert into numpy array

ht_np = np.array(hg_in)

#convert height from inch to meter by exposing it to 0.0245
ht_np = ht_np * 0.0245

ht_np

array([1.4945, 1.617 , 1.764 , 1.6905, 2.156 , 2.401 , 1.1025, 1.617 ,
       1.519 , 1.8865, 1.911 ])

In [8]:
#weight of players in pound

wt_pd = [70, 80, 90, 99, 76, 86, 67, 78, 89, 88, 97,]

#convert into array
wt_np = np.array(wt_pd)

#convert height from pound to kg by exposing it to 0.45
wt_np = wt_np*0.45

wt_np

array([31.5 , 36.  , 40.5 , 44.55, 34.2 , 38.7 , 30.15, 35.1 , 40.05,
       39.6 , 43.65])

In [9]:
#BMI calculation 

BMI = wt_np/(ht_np**2)
BMI

array([14.10323411, 13.76836786, 13.01541025, 15.58896773,  7.35747158,
        6.71315454, 24.80447961, 13.42415867, 17.35749196, 11.12708913,
       11.95261343])

In [10]:
BMI[-1]

11.952613432765933

In [11]:
BMI[BMI<2]

array([], dtype=float64)

In [17]:
BMI[:5]

array([14.10323411, 13.76836786, 13.01541025, 15.58896773,  7.35747158])

In [14]:
players = np.array([wt_np,ht_np])
players

array([[31.5   , 36.    , 40.5   , 44.55  , 34.2   , 38.7   , 30.15  ,
        35.1   , 40.05  , 39.6   , 43.65  ],
       [ 1.4945,  1.617 ,  1.764 ,  1.6905,  2.156 ,  2.401 ,  1.1025,
         1.617 ,  1.519 ,  1.8865,  1.911 ]])

In [15]:
players[0][2]


40.5

In [19]:
players[1][2]


1.764

In [20]:
players[1]

array([1.4945, 1.617 , 1.764 , 1.6905, 2.156 , 2.401 , 1.1025, 1.617 ,
       1.519 , 1.8865, 1.911 ])

In [23]:
#Transpose 

pT = players.transpose()
pT.shape

(11, 2)

In [24]:
pT = players.transpose()
pT

array([[31.5   ,  1.4945],
       [36.    ,  1.617 ],
       [40.5   ,  1.764 ],
       [44.55  ,  1.6905],
       [34.2   ,  2.156 ],
       [38.7   ,  2.401 ],
       [30.15  ,  1.1025],
       [35.1   ,  1.617 ],
       [40.05  ,  1.519 ],
       [39.6   ,  1.8865],
       [43.65  ,  1.911 ]])

In [30]:
#statistical and mathematical function on players data

print(np.mean(wt_np))

print(np.median(wt_np))

print(np.sum(wt_np))

#standard deviation
print(np.std(wt_np))

#correlation coefficient
print(np.corrcoef(wt_np,ht_np))


37.63636363636364
38.7
414.00000000000006
4.44762913906698
[[1.        0.4052948]
 [0.4052948 1.       ]]
